TP2 first iteration
UPB-FILS-ALF/upb-fils-alf.github.io pull request #10
Opened 2024-02-11 16:39 UTC by mihaicostin34

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Your Name <Your Email@example.com>

2024-02-12 10:32 UTC, alexandruradovici requested changes
Make sure you install katex https://docusaurus.io/docs/markdown-features/math-equations, otherwise math symbols do not work.

2024-02-12 10:32 UTC, alexandruradovici commented on docs/tp/02.md
> +- un ensemble d’états F, un sous-ensemble de S, nomé états finals.
```suggestion
- un ensemble d’états F, un sous-ensemble de $S$, nomé états finals.
```

2024-02-12 10:33 UTC, alexandruradovici commented
Please fill out the pull request template.

2024-02-14 07:58 UTC, alexandruradovici commented on docs/tp/03.md
> +<br></br>
Do we need this line?

2024-02-14 13:25 UTC, CAmi307 commented on docs/tp/03.md
> +Pour un compilateur, au commencement du processus de compilation, tout fichier avec du code est vu comme un chaîne de caractères dans lequel il faut identifier les mots composantes et les partager da
```suggestion
Pour un compilateur, au commencement du processus de compilation, tout fichier avec de code est vu comme un chaîne de caractères dans lequel il faut identifier les mots composantes et les partager dans des jetons (*tokens*). Pour faire cela, on a besoin d’une méthode de reconnaître certaines sous-chaînes dans le texte initial. Les automates finis offrent une bonne solution à ce problème.
```

2024-02-14 13:36 UTC, CAmi307 commented on docs/tp/03.md
> +:::
Did you explain how to compute the transition function?

2024-02-14 15:00 UTC, Ioan-Cristian commented on docs/tp/03.md
> +3. Remplissez la classe ```DFA.kt``` dans les fichiers du TP. Utilisez l’implémentation obtenue pour un automate qui cherche le modèle "aabab". Affichez les positions des occurences du modèle dans le
```suggestion
3. Remplissez la classe ```DFA.kt``` dans les fichiers du TP. Utilisez l’implantation obtenue pour un automate qui cherche le modèle "aabab". Affichez les positions des occurences du modèle dans la chaîne "aaababaabaababaab" 
```

2024-02-14 15:10 UTC, mihaicostin34 commented on docs/tp/03.md
> +<br></br>
I thought it would be a good idea to tell them this (just to give them a bit more information). It is not essential, we can remove it if needed

2024-02-14 15:27 UTC, mihaicostin34 commented on docs/tp/03.md
> +Le pseudo-code d’un automate fini avec l’état initial $0$, le seul état final $m$ et la fonction de transition $f$ qui doit reconnaître un modèle $P$ de longueur $m$ dans un texte $T$ de longueur $n$
Why put "pour le" since the pseudocode is what follows this paragraph? We can maybe change it to "Le pseudocode **pour** un automate?

2024-02-14 15:35 UTC, Ioan-Cristian commented on docs/tp/03.md
> +Le pseudo-code d’un automate fini avec l’état initial $0$, le seul état final $m$ et la fonction de transition $f$ qui doit reconnaître un modèle $P$ de longueur $m$ dans un texte $T$ de longueur $n$
La conjonction *pour* sert à lier le groupe nominal *le pseudo-code d'un automate fini avec l'état initial $0$* du reste de la phrase. Sans *pour*, c'est une phrase sans prédicat. En tous cas selon moi. :)

2024-02-14 17:52 UTC, Ioan-Cristian submitted a review, later dismissed

2024-02-14 18:46 UTC, alexandruradovici commented on docs/tp/03.md
> +<br></br>
The `<br>` tag?

2024-02-14 18:46 UTC, alexandruradovici commented on docs/tp/03.md
> +<br></br>
```suggestion
```

2024-02-15 07:57 UTC, mihaicostin34 commented on docs/tp/03.md
> +<br></br>
Sorry, I misunderstood. The ```<br>``` tag is nto really necessary. Initially I thought it looked better with the extra spacing, but it doesn't make a big difference.

2024-02-16 12:57 UTC, alexandruradovici requested changes

2024-02-16 12:57 UTC, alexandruradovici commented on docs/tp/03.md
> +    val pattern: String,         // le modèle à trouver
This is not part of an DFA, but actually deduced from the transition mappings.

2024-02-16 12:57 UTC, alexandruradovici commented on docs/tp/03.md
> +                print("On a trouvé P dans T")
This is not clear to me, why `q==m`?

2024-02-16 12:57 UTC, alexandruradovici commented on docs/tp/03.md
> +````
```suggestion
```kotlin
    fun compute_transition_function(P, S'): 
        val m = P.length
        for q=0 to m:
            for a in S' :
                var k = min(m+1, q.index()+2)
                repeat:
                    k = k-1                 
                until P[0..k] is a suffix for (P[0..q] || a)
                f(q, a) = k
        return f    
```
```

2024-02-16 12:57 UTC, alexandruradovici commented on docs/tp/03.md
> +````
I am not sure that I understand the code. This seems to complicated for the lab, I would rather they write the functions themselves, not deduce it.

2024-02-16 12:57 UTC, alexandruradovici commented on docs/tp/03.md
> +3. Remplissez la classe ```DFA.kt``` dans les fichiers du TP. Utilisez l'implantation obtenue pour un automate qui cherche le modèle "aabab". Affichez les positions des occurences du modèle dans la c
```suggestion
3. Remplissez la classe `DFA.kt` dans les fichiers du TP. Utilisez l'implantation obtenue pour un automate qui cherche le modèle "aabab". Affichez les positions des occurences du modèle dans la chaîne "aaababaabaababaab" 
```

use single reversed quotes for inline code.

2024-02-20 09:52 UTC, Ioan-Cristian submitted a review, later dismissed

2024-02-20 14:58 UTC, alexandruradovici requested changes

2024-02-20 14:58 UTC, alexandruradovici commented on docs/tp/03.md
I suggest creating a folder `03` that contains an `index.md` and all the resources.

2024-02-21 11:50 UTC, alexandruradovici commented on docs/tp/03.md
Take a look at the `intro` page.

2024-02-21 15:38 UTC, mihaicostin34 commented on docs/tp/03.md
Done for tp03 and tp01 individually

2024-02-22 10:31 UTC, alexandruradovici requested changes
Can you split this in two pull requests? One for TP03 and the other for the changes in TP01?

2024-02-22 15:34 UTC, mihaicostin34 commented
> Can you split this in two pull requests? One for TP03 and the other for the changes in TP01?

Moved to PR #16

2024-02-22 18:05 UTC, alexandruradovici requested changes
Please rebase this.

2024-02-23 17:13 UTC, merged