Add introduction
UPB-FILS-ALF/upb-fils-alf.github.io pull request #12
Opened 2024-02-14 12:32 UTC by alexandruradovici

### Pull Request Overview

This pull request adds the introduction page describing:
- the subjects
- the grading
- the team

### Testing Strategy

This pull request was tested by Alexandru Radovici.

### TODO or Help Wanted

This pull request still needs feedback.

### Build

- [x] Ran `npm build`.

### Author

Signed-off-by: Alexandru Radovici <alexandru.radovici@upb.ro>

2024-02-14 12:57 UTC, CAmi307 commented
Can we align all 3 photos on the same line? Or at least have them centered

2024-02-14 13:11 UTC, CAmi307 commented on docs/intro/index.md
> +| 1220B 1/2 | Mardi | 10 - 12 | EG 306 |
```suggestion
| Activite | Goupe | Jour | Heure | Salle |
|-------|-------|------|-------|-------|
| Cours | 1220 | Jeudi | 10 - 12 | PR002 |
| Laboratoire | 1220A - sousgroupe 2 | Mardi | 8 - 10 | EG 306 |
| Laboratoire | 1220A - sousgroupe 1 | Mardi | 10 - 12 | EG 306 |
| Laboratoire | 1220B - sousgroupe 2 | Mardi | 8 - 10 | EG 306 |
| Laboratoire | 1220B - sousgroupe 1 | Mardi | 10 - 12 | EG 306 |
```

2024-02-14 13:13 UTC, CAmi307 commented on docs/intro/index.md
> +3. Vous pouvez motivez l’absence au TP(raison medical) dans maximum 2 semaines de la date de votre absence
Two weeks feels like a lot of time to provide a fake medical paper, what do you think?

2024-02-14 13:14 UTC, CAmi307 commented on docs/intro/index.md
> +6. Les étudiants qui rattrapent la matière peuvent pas participer aux TPs seulement s'il y a des places libres. Afin d'obtenir des points, ils doivent résoudre des devoirs et passer l'examen final
```suggestion
6. Les étudiants qui rattrapent la matière peuvent participer aux TPs seulement s'il y a des places libres. Afin d'obtenir des points, ils doivent résoudre des devoirs et passer l'examen final
```

2024-02-14 13:17 UTC, CAmi307 commented on docs/intro/index.md
> +# Bienvenue
```suggestion
# Introduction
```

"Bienvenue" could be confused with just a title. What do you think?

2024-02-14 13:18 UTC, CAmi307 commented on docs/intro/index.md
> +Devoir \
```suggestion
Responsable des devoirs \
```

I'm not a homework :))))

2024-02-14 14:02 UTC, Ioan-Cristian requested changes

2024-02-14 14:02 UTC, Ioan-Cristian commented on docs/intro/index.md
> +| 1220B 1/2 | Mardi | 10 - 12 | EG 306 |
**sous groupe**.

2024-02-14 14:51 UTC, mihaicostin34 commented on docs/intro/index.md
> +| Tests de cours | Vous passerez un test au début de chaque cours avec des questions du cours précédent. | 2p |
| Tests de cours | Vous passerez un test au début de chaque cours avec des questions sur le cours précédent. | 2p |

2024-02-14 14:53 UTC, mihaicostin34 commented on docs/intro/index.md
> +| Tests de TP | Vous passerez un test au début de chaque laboratoire avec des questions du laboratoire précédent. | 3p |
questions **sur le** laboratoire

2024-02-14 14:55 UTC, mihaicostin34 commented on docs/intro/index.md
> +Tout au long du cours, vous apprendrez comment fonctionnent les processeurs informatiques, les langages de programmation et comment les compilateurs transforment un langage de haut niveau en code lis
vous **apprenez**

2024-02-14 14:57 UTC, mihaicostin34 commented on docs/intro/index.md
> +| **Total** | *Vous avez besoin de 4,5 points pour réussir le cours.* | **15p** |
Maybe move the 4.5 points rule to the "Règles" section?

2024-02-14 15:03 UTC, mihaicostin34 commented on docs/intro/index.md
> +3. Vous pouvez motivez l’absence au TP(raison medical) dans maximum 2 semaines de la date de votre absence
maximum 2 semaines dès la date de votre absence

2024-02-14 15:07 UTC, mihaicostin34 commented on docs/intro/index.md
> +5. **John E. Hopcroft, Rajeev Motwani, Jeffrey D. Ullman**, *Introduction to Automata Theory, Languages, and Computation, 3rd Edition
```suggestion
5. **John E. Hopcroft, Rajeev Motwani, Jeffrey D. Ullman**, *Introduction to Automata Theory, Languages, and Computation, 3rd Edition*
```

2024-02-15 07:56 UTC, CAmi307 commented on docs/intro/index.md
> +| **Total** | *Vous avez besoin de 4,5 points pour réussir le cours.* | **15p** |
It is also present in the "Règles" section if not mistaken

2024-02-15 08:32 UTC, alexandruradovici commented on docs/intro/index.md
> +# Bienvenue
Not sure about this, @mihaicostin34 ?

2024-02-15 08:33 UTC, alexandruradovici commented on docs/intro/index.md
> +Email: amalia.simion@wyliodrin.com
That works, it will be with `stud` though. If that is fine for you, sure, please update it. @mihaicostin34 same for you.

2024-02-15 08:34 UTC, alexandruradovici commented on docs/intro/index.md
> +3. Vous pouvez motivez l’absence au TP(raison medical) dans maximum 2 semaines de la date de votre absence
What about the first time when he or she comes back to the lab?

2024-02-15 08:35 UTC, CAmi307 commented on docs/intro/index.md
> +Email: amalia.simion@wyliodrin.com
I prefer the updating it with the university account.

2024-02-15 08:38 UTC, alexandruradovici commented on docs/intro/index.md
> +3. Vous pouvez motivez l’absence au TP(raison medical) dans maximum 2 semaines de la date de votre absence
@Ioan-Cristian please suggest the change using github's `suggest changes` utility.

2024-02-15 08:39 UTC, alexandruradovici commented on docs/intro/index.md
> +| **Total** | *Vous avez besoin de 4,5 points pour réussir le cours.* | **15p** |
Repetition is good.

2024-02-15 08:41 UTC, alexandruradovici commented on docs/intro/index.md
> +3. Vous pouvez motivez l’absence au TP(raison medical) dans maximum 2 semaines de la date de votre absence
@CAmi307 might be right about this, @mihaicostin34 see above.

2024-02-15 08:43 UTC, CAmi307 commented on docs/intro/index.md
> +3. Vous pouvez motivez l’absence au TP(raison medical) dans maximum 2 semaines de la date de votre absence
Discussed with Cristiana and Mihai, two weeks is ok.

2024-02-15 08:47 UTC, alexandruradovici commented
> Can we align all 3 photos on the same line? Or at least have them centered

What about now? I used a table.

2024-02-15 13:41 UTC, alexandruradovici commented on docs/intro/index.md
> +Email: amalia.simion@wyliodrin.com
Please suggest the change here.

2024-02-15 14:34 UTC, mihaicostin34 commented on docs/intro/index.md
> +Email: amalia.simion@wyliodrin.com
```suggestion
Email: amalia.simion@stud.fils.upb.ro
```

2024-02-15 14:37 UTC, mihaicostin34 requested changes

2024-02-15 14:37 UTC, mihaicostin34 commented on docs/intro/index.md
> +Email: mihai.costin@wyliodrin.com
```suggestion
Email: mihai.costin@stud.fils.upb.ro
```

2024-02-15 14:37 UTC, mihaicostin34 commented on docs/intro/index.md
> +mihai.costin@wyliodrin.com
```suggestion
mihai.costin@stud.fils.upb.ro
```

2024-02-15 14:37 UTC, mihaicostin34 commented on docs/intro/index.md
> +amalia.simion@wyliodrin.com
```suggestion
amalia.simion@stud.fils.upb.ro
```

2024-02-16 12:18 UTC, alexandruradovici commented on docs/intro/index.md
> +Email: amalia.simion@wyliodrin.com
@CAmi307 please add your email here.

2024-02-19 09:07 UTC, Ioan-Cristian approved these changes

2024-02-19 14:32 UTC, alexandruradovici commented
@CAmi307 @mihaicostin34 please set the rule for absences to be able to merge this.

2024-02-19 18:11 UTC, mihaicostin34 approved these changes

2024-02-19 18:17 UTC, mihaicostin34 commented on docs/intro/index.md
> +Comme devoir, vous construirez votre propre petit compilateur de langage qui génère du code [WebAssembly](https://webassembly.org/) (*WASM*).
```suggestion
Comme devoir, vous construiriez votre propre petit compilateur de langage qui génère du code [WebAssembly](https://webassembly.org/) (*WASM*).
```

2024-02-19 18:19 UTC, mihaicostin34 commented
> @CAmi307 @mihaicostin34 please set the rule for absences to be able to merge this.
What do you mean, exactly?

2024-02-20 12:55 UTC, alexandruradovici commented
> > @CAmi307 @mihaicostin34 please set the rule for absences to be able to merge this.
> 
> 
> 
> What do you mean, exactly? 
> 
> 

I was talking about the policy of lab absences.

2024-02-20 14:01 UTC, mihaicostin34 commented
> > > @CAmi307 @mihaicostin34 please set the rule for absences to be able to merge this.
> > 
> > 
> > What do you mean, exactly?
> 
> I was talking about the policy of lab absences.

Yes, 2 weeks is fine

2024-02-20 14:21 UTC, alexandruradovici commented
@CAmi307 @mihaicostin34 please approve so we can merge this.

2024-02-20 14:56 UTC, mihaicostin34 approved these changes

2024-02-20 14:59 UTC, CAmi307 approved these changes

2024-02-20 15:00 UTC, merged