Tp4
UPB-FILS-ALF/upb-fils-alf.github.io pull request #14
Opened 2024-02-20 20:53 UTC by mihaicostin34

### Pull Request Overview

This pull request adds TP4 - RegEx

### Testing Strategy

This pull request was tested by running `npm run start`

### TODO or Help Wanted

This pull request still needs a second opinion on the exercices: I would like to keep the site from ex 1 because I find it quite useful and 4 because it is interesting. I just don't want them to feel like there are too many exercices.

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Mihai Costin <mihaicostin342@gmail.com>

2024-02-22 10:34 UTC, alexandruradovici requested changes

2024-02-22 10:34 UTC, alexandruradovici commented on docs/tp/04.md
> +#### Description avancée de modèles
There does not seem to be any text here for this subsection?

2024-02-22 10:34 UTC, alexandruradovici commented on docs/tp/04.md
> +|Expréssion|Correspond à|Exemple|
I would split this in two tables:
1. regex in math
2. extension of regex in Kotlin

2024-02-22 10:34 UTC, alexandruradovici commented on docs/tp/04.md
> +## Exercices
I would add an extra exercise to recognize some file from the system, like `/etc/passwd`.

2024-02-22 15:36 UTC, mihaicostin34 commented on docs/tp/04.md
> +#### Description avancée de modèles
I added another header for each TP because the second header after the title also appears in the page with all the TPs
![image](https://github.com/UPB-FILS-ALF/upb-fils-alf.github.io/assets/101063308/6db337de-7acb-4d66-a878-05744eaccb6b)
And I added it as a subtitle/short description of the TP contents (otherwise, for TP02 we would have "Objectifs du TP" written under the main name as a subtitle

2024-02-22 15:48 UTC, mihaicostin34 commented on docs/tp/04.md
> +|Expréssion|Correspond à|Exemple|
What do you mean by this, exactly? As far as I know, kotlin doesn't add new regex operators to the ones taken from math

2024-02-22 18:12 UTC, alexandruradovici commented on docs/tp/04.md
> +#### Description avancée de modèles
I think you can use the description metadata https://docusaurus.io/docs/create-doc.

2024-02-22 18:12 UTC, alexandruradovici requested changes

2024-02-23 11:55 UTC, alexandruradovici requested changes

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +|c|Le caractère 'c'.| a|
```suggestion
|a|Le caractère `a`.| `a`|
```

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +|\c|Le caractère lui-même (on utilise cet opérateur quand on veut avoir des caractères qui d’habitude sont des opérateurs).| \\* |
This is not clear, I would add this as a note.

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +|"s"|La chaîne s.| "abcca"|
```suggestion
|"abcca"|La chaîne "abcca".| "abcca"|
```

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +|r\{m, n\}| Entre m et n occurences de r.| a{3, 7}|
Kotlin extension

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +|r1r2| La chaîne r1 suivi par r2.| ab |
Is this a rule?

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +|\\w| Alphanumérique et _ .| \\w |
Kotlin specific

2024-02-23 11:55 UTC, alexandruradovici commented on docs/tp/04.md
> +| a-z |Intervalle. | 0-9|
```suggestion
| [a-z] |Intervalle. | [0-9]|
```

2024-02-23 14:27 UTC, mihaicostin34 commented on docs/tp/04.md
> +|r1r2| La chaîne r1 suivi par r2.| ab |
Line 29? Not necessarily, I think we can remove it if it is redundant

2024-02-23 17:17 UTC, alexandruradovici requested changes

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|.|Remplace tout caractère que la ligne nouvelle (`newline`).| a.b|
I think the point replaces any character, including newline.

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|^|Commencement de la ligne. | ^abc|
```suggestion
|^|Commencement du text. | ^abc|
```

^ states that the match has to start at the beginning of the text. Regex matches try to match parts of a string, that might not be at the beginning.

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|$|Fin de la ligne. | abc$|
```suggestion
|$|Fin du text. | abc$|
```

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|\[s\]|L’un des caractères de la chaîne "s".| \[abc\] |
```suggestion
|\[abc...\]|L’un des caractères de la ensable $$\Set{a,b,c,...}\$$.| \[abc\] |
```

The latex might not be exactly right.

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|\[^s\]|Tout caractère qui ne se trouve pas dans la chaîne "s".| \[^abc\] |
Similar as above, the complementary set.

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +| [a-z] |Intervalle. | [0-9]|
The set of symbols in the interval.

2024-02-23 17:17 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|Expréssion|Correspond à|Exemple|
Add a note saying that most of the programming languages have regex support, and that the way they declared might be different.

2024-02-24 13:35 UTC, mihaicostin34 commented on docs/tp/tp04/index.md
> +|.|Remplace tout caractère que la ligne nouvelle (`newline`).| a.b|
I could only find sources saying it replaces anything but newline

2024-02-24 20:05 UTC, alexandruradovici commented on docs/tp/tp04/index.md
> +|.|Remplace tout caractère que la ligne nouvelle (`newline`).| a.b|
That is not true for sure in ANTLR and can be seen in regex101 https://regex101.com/r/Omv4jZ/1

2024-02-24 20:11 UTC, alexandruradovici requested changes

2024-02-24 20:11 UTC, alexandruradovici commented on docs/tp/04/index.md
> +| [0-9] |Intervalle. | [0-9]|
Please explain this.

2024-02-24 20:11 UTC, alexandruradovici commented on docs/tp/04/index.md
> +Si on a besoin d’utiliser dans un RegEx la valeur d’caractère qui est aussi un opérateur (\*, \?, \^), il faut ajouter un "\\" devant lui: "\\*", "\\?", "\\^".
Use `::tip`

2024-02-24 20:11 UTC, alexandruradovici commented on docs/tp/04/index.md
> +## Sources
```suggestion
## Bibliographie
```
Maybe rename it?

2024-02-24 20:11 UTC, alexandruradovici commented on docs/tp/04/index.md
> +- *Introduction to Automata Theory, Languages and Computation - 3rd edition*- Chapitre 3: Regular Expressions
Use a numbered list fir these.

2024-02-25 13:33 UTC, mihaicostin34 commented on docs/tp/tp04/index.md
> +|.|Remplace tout caractère que la ligne nouvelle (`newline`).| a.b|
In regex101 it has to highlight the newline if it matches it, like here https://regex101.com/r/XCJ6zW/1 
I also tested it with kotlin regex and it does not match, so in the first table I modified it to say that . matches everything and I added one more line on the kotlin extension saying it does not match newline (just for kotlin)

2024-02-25 13:36 UTC, alexandruradovici approved these changes

2024-02-25 13:38 UTC, merged