Added Dev1 text
UPB-FILS-ALF/upb-fils-alf.github.io pull request #24
Opened 2024-02-27 10:51 UTC by mihaicostin34

### Pull Request Overview

This pull request adds Dev1

### Testing Strategy

This pull request was tested by running `npm run start`

### TODO or Help Wanted

This pull request still needs a link for the homework assignment

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Mihai Costin <mihaicostin342@gmail.com>

2024-02-29 07:48 UTC, alexandruradovici commented on docs/devoir/01.md
> +1. Vous ne pouvez pas utiliser RegEx ou toute autre bibliothèque qui utilise des expressions régulières (sauf \n\r? pour séparer les lignes d'entrée de la source).
```suggestion
1. Vous ne pouvez pas utiliser `RegEx` ou toute autre bibliothèque qui utilise des expressions régulières (sauf \n\r? pour séparer les lignes d'entrée de la source).
```

2024-02-29 07:48 UTC, alexandruradovici commented on docs/devoir/01.md
> +Les devoirs sont individuels. Toute tentative de tricher entraînera 0p pour les devoirs. Un système anti-copie automatisé sera utilisé.
use `:::error`

2024-02-29 13:08 UTC, mihaicostin34 commented
> Looks really good, please add a full example, the input file and the output text.

Added a basic example

2024-02-29 16:23 UTC, alexandruradovici requested changes

2024-02-29 16:23 UTC, alexandruradovici commented on docs/devoir/01.md
> +    push 20
Please add a comment explaining what each instruction does.

2024-03-03 18:48 UTC, alexandruradovici requested changes

2024-03-03 18:48 UTC, alexandruradovici commented on docs/devoir/01.md
> +:::
```suggestion
:::info
    Deadline: le 17 mars \
    Points: 2 points de la note finale \
    Lien: https://classroom.github.com/a/s3tmWRAY \
    Téléchargement tardif: **1p/jour** (maximum 2 jours) 
:::
```

2024-03-03 18:48 UTC, alexandruradovici commented on docs/devoir/01.md
> +               ; la pile est [ ]
Comments are used with `;`, but in the examples are with `#`. I suggest using one of them.

Please add a statement explaining that every line that starts with the comment symbol should be ignored.

2024-03-03 18:48 UTC, alexandruradovici commented on docs/devoir/01.md
> +    push 20     #ajoute 20 à la pile
I suggest placing all the comments into one single line and adding that comments will not be placed like that in the test files.

2024-03-03 18:50 UTC, alexandruradovici commented on docs/devoir/01.md
> +Si vous avez des questions concernant les devoirs, posez-les en publiant un problème sur le [github repository pour les questions](https://github.com/UPB-FILS-ALF/questions) avec le format du titre [
```suggestion
Si vous avez des questions concernant les devoirs, posez-les en publiant un problème sur le [github repository pour les questions](https://github.com/UPB-FILS-ALF/questions) avec le format du titre `[simulator]\<titre de votre question\>`. Vous aurez besoin d'un compte github pour cela. 
```

2024-03-03 18:51 UTC, alexandruradovici requested changes

2024-03-03 18:51 UTC, alexandruradovici commented on docs/devoir/01.md
> +                jump 2 ; ERROR (mul): invalid jump address 2
```suggestion
                jump 2 ; ERROR (jump): invalid jump address 2
```

2024-03-03 19:57 UTC, alexandruradovici requested changes

2024-03-03 19:57 UTC, alexandruradovici commented on docs/devoir/01.md
> +    Téléchargement tardif: **1p/jour** (maximum 2 jours)
```suggestion
    Deadline: le 17 mars \
    Points: 2 points de la note finale \
    Lien: https://classroom.github.com/a/s3tmWRAY \
    Téléchargement tardif: **1p/jour** (maximum 2 jours) 
```

2024-03-03 19:59 UTC, alexandruradovici approved these changes

2024-03-03 20:01 UTC, merged