Tp05
UPB-FILS-ALF/upb-fils-alf.github.io pull request #25
Opened 2024-02-28 17:24 UTC by mihaicostin34

### Pull Request Overview

This pull request adds TP5

### Testing Strategy

This pull request was tested by running `npm run start`

### TODO or Help Wanted

This pull request still needs an opinion on the theory part.

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Mihai Costin <mihaicostin342@gmail.com>

2024-02-29 10:45 UTC, Ioan-Cristian commented on docs/tp/04/index.md
> +À partir de ce TP, on va utiliser ANTLR pour l’analyse du texte. ANTLR (Another Tool For Language Recognition) est un outil pour generer des analyseurs (parsers) qui permettent le traitement, l’exécu
```suggestion
À partir de ce TP, on va utiliser ANTLR pour l’analyse du texte. ANTLR (Another Tool For Language Recognition) est un outil pour générer des analyseurs (parsers) qui permettent le traitement, l’exécution et la traduction du code. On va employer ANTLR pour la partie front-end de notre compilateur.
```

2024-02-29 10:45 UTC, Ioan-Cristian commented on docs/tp/04/index.md
> +En ANTLR, on peut même utiliser des productions pour décrire les jétons. Dans ce cas, le corps de la production doit contenir que des jétons. On va identifier les jétons avec des noms qui commencent
```suggestion
En ANTLR, on peut utiliser des productions pour décrire des jétons. Dans ce cas, le corps de la production doit contenir que des jétons. On va identifier les jétons avec des noms qui commencent avec des lettres **MAJUSCULES** (On vous conseile d’utiliser que des majuscules pour les jétons, pour pouvoir les distinguer plus facilement). D’habitude, on trouve les définitions des jétons à la fin de la grammaire.
```

2024-02-29 10:45 UTC, Ioan-Cristian commented on docs/tp/04/index.md
> +1. Ouvrez les fichiers du laboratoire. Dans TP04/ex1.g4, completez les `TODO` pour écrire une grammaire qui reconnaît une instruction de déclaration d'une variable, ayant la syntaxe suivante:
```suggestion
1. Ouvrez les fichiers du laboratoire. Dans TP04/ex1.g4, complétez les `TODO` pour écrire une grammaire qui reconnaît une instruction de déclaration d'une variable, ayant la syntaxe suivante:
```

2024-02-29 10:45 UTC, Ioan-Cristian commented on docs/tp/04/index.md
> +- le nom du type est l'un des options suivantes: `int`, `long`, `bool`, `char`
```suggestion
- le nom du type est l'une des options suivantes: `int`, `long`, `bool`, `char`
```

2024-02-29 10:45 UTC, Ioan-Cristian commented on docs/tp/04/index.md
> +2. Ouvrez les fichiers du laboratoire. Dans TP04/ex2.g4, completez les `TODO` pour écrire une grammaire qui reconnaît des expréssions mathématiques avec des nombres entières et des noms de variables.
```suggestion
2. Ouvrez les fichiers du laboratoire. Dans TP04/ex2.g4, complétez les `TODO` pour écrire une grammaire qui reconnaît des expréssions mathématiques avec des entiers et des noms de variables.
```

2024-02-29 10:46 UTC, Ioan-Cristian commented
Peut-être changer le nom de la demande d'ajout (pull request) en TP04 ? :)

2024-03-11 18:35 UTC, alexandruradovici requested changes

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +# 04- Grammaires indépendantes de contexte
```suggestion
# 04 - Grammaires indépendantes de contexte
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +$$
```suggestion
$$
  P \rightarrow S + S
$$

$$
  S \rightarrow 0S1
$$

$$
  S \rightarrow \epsilon 
$$
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +- les terminaux: 0 et 1
```suggestion
- les terminaux: $$\{+, 0, 1\}$$
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +- les non-terminaux: P, S
```suggestion
- les non-terminaux: $$\{P, S\}$$
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +- le symbole de début: P
```suggestion
- le symbole de début: $$P$$ 
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +- \+
```suggestion
- `00001111+0011`
- `01+0011`
- `+01`
- `+`
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +### Variables
```suggestion
### Règles
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +On va identifier les variables avec des lettres **minuscules**.
```suggestion
On va identifier les règles avec des lettres **minuscules**.
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +En ANTLR, on **ne peut pas avoir des productions avec la même tête**. Ce qu’on peut faire, c’est de mettre les deux corps dans un seul et de les séparer avec l’opérateur `|`.
```suggestion
En ANTLR, on **ne peut pas avoir des règles avec la même tête**. Ce qu’on peut faire, c’est de mettre les deux corps dans un seul et de les séparer avec l’opérateur `|`.
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +  assignment: VARIABLE_NAME '=' INTEGER ; //une variable pour représenter une affectation
```suggestion
  assignment: VARIABLE_NAME '=' INTEGER ; //une règle pour représenter une affectation
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +  //une variable pour représenter une expression d'addition
```suggestion
  //une règle pour représenter une expression d'addition
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +par la valeur `01`.
You can have the empty rule:

```antlr4
grammar demo;

ZERO: '0';
ONE: '1'; 

p : s '+' s;
s : ZERO s ONE  
  | ; 
```

I might be wrong about this, please try it out before changing.

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +ONE: '1';
I would writing the tokens first.

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +1. Ouvrez les fichiers du laboratoire. Dans TP04/ex1.g4, completez les `TODO` pour écrire une grammaire qui reconnaît une instruction de déclaration d'une variable, ayant la syntaxe suivante:
```suggestion
1. Ouvrez les fichiers du laboratoire. Dans `TP04/ex1.g4`, completez les `TODO` pour écrire une grammaire qui reconnaît une instruction de déclaration d'une variable, ayant la syntaxe suivante:
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +2. Ouvrez les fichiers du laboratoire. Dans TP04/ex2.g4, completez les `TODO` pour écrire une grammaire qui reconnaît des expréssions mathématiques avec des nombres entières et des noms de variables.
```suggestion
2. Ouvrez les fichiers du laboratoire. Dans `TP04/ex2.g4`, completez les `TODO` pour écrire une grammaire qui reconnaît des expréssions mathématiques avec des nombres entières et des noms de variables.
```

2024-03-11 18:35 UTC, alexandruradovici commented on docs/tp/04/index.md
> +3. Ouvrez les fichiers du laboratoire. Dans TP04/ex3.g4, combinez les deux grammaires des exercices précédents pour obtenir une grammaire qui accepte les instructions suivantes:
```suggestion
3. Ouvrez les fichiers du laboratoire. Dans `TP04/ex3.g4`, combinez les deux grammaires des exercices précédents pour obtenir une grammaire qui accepte les instructions suivantes:
```

2024-03-11 18:35 UTC, alexandruradovici commented on docusaurus.config.ts
> +export default config;
```suggestion
export default config;

```

Add newline.

2024-03-20 20:24 UTC, alexandruradovici approved these changes

2024-03-20 20:27 UTC, merged