Tp05
UPB-FILS-ALF/upb-fils-alf.github.io pull request #31
Opened 2024-03-19 15:57 UTC by mihaicostin34

### Pull Request Overview

This pull request adds TP05 - Lexer and Parser with ANLTR

### Testing Strategy

This pull request was tested by running `npm run start`

### TODO or Help Wanted

This pull request still needs a review of the exercices and the parser theory

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Mihai Costin <mihaicostin342@gmail.com>

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +Le **Lexer** est une composante du compilateur. Son but est de lire le texte d’entrée (qui est notre programme source) et de produire en tant que sortie une **séquence de jétons**. Les erreurs qui ap
```suggestion
Le **Lexer** est une composante du compilateur. Son but est de lire le texte d’entrée (qui est notre programme source) et de produire en tant que sortie une **séquence de jétons**. Les erreurs qui apparaissent au niveau du **Lexer** sont des **erreurs d’analyze lexicale**.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +- le **modèle** est une description de la forme que les lexemes d’un jéton peuvent avoir. Si le jéton représent un mot clé (par exemple, le mot clé if), le jétons est une chaîne de caractères qui com
```suggestion
- le **modèle** est une description de la forme que les lexèmes d’un jéton peuvent avoir. Si le jéton représente un mot clé (par exemple, le mot clé if), le jéton est une chaîne de caractères qui composent le mot. Pour d’autres situations (par exemple, pour définir des noms pour les variables), on utilise des expressions plus complexes (comme les RegEx).
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +- le **lexeme** est une séquence de caractères dans le programme source qui correspond au modèle d’un jéton et est identifié par le Lexer comme une instance du jéton.
```suggestion
- le **lexème** est une séquence de caractères dans le programme source qui correspond au modèle d’un jéton et est identifié par le Lexer comme une instance du jéton.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +Le Parser obtient la séquence de jétons produite par le Lexer et vérifie si elle peut être générée par la grammaire du langage source. La sortie du Parser est l’arbre d’analyze (Parse Tree). Les erre
```suggestion
Le Parser obtient la séquence de jétons produite par le Lexer et vérifie si elle peut être générée par la grammaire du langage source. La sortie du Parser est l’arbre d’analyse (Parse Tree). Les erreurs qui apparaissent au niveau du Parser sont des **erreurs d’analyse syntaxique**.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +  //une règles pour représenter une expression d'addition
```suggestion
  //une règle pour représenter une expression d'addition
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +Au lieu d’écrire vous-même le lexer et le parser, ANTLR peut les générer automatiquement à partir de votre grammaire. Vous devez seulement les utiliser dans votre code.
```suggestion
Au lieu d’écrire vous-mêmes le lexer et le parser, ANTLR peut les générer automatiquement à partir de votre grammaire. Vous devez seulement les utiliser dans votre code.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +Le fichier avec la grammaire doit se trouver sous le chemin `src/main/antlr`. Après la génération, vous trouvez aussi le dossier `.antlr`, qui contient toutes les fichiers générés par antlr.
```suggestion
Le fichier avec la grammaire doit se trouver sous le chemin `src/main/antlr`. Après la génération, vous trouvez aussi le dossier `.antlr`, qui contient tous les fichiers générés par antlr.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +Pour utiliser cettes nouveaux fichiers dans votre code, il faut seulement instantier les classes.
```suggestion
Pour utiliser ces nouveaux fichiers dans votre code, il faut seulement instantier les classes.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +  Les noms du lexer et parser auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusieur
```suggestion
  Les noms du lexer et parser auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusieurs détails sur ces classes et les méthodes qu’elles exposent, on vous conseille d’ouvrir la documentation: [lexer](https://www.antlr.org/api/Java/org/antlr/v4/runtime/Lexer.html) et [parser](https://www.antlr.org/api/Java/org/antlr/v4/runtime/Parser.html).
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +Les methodes du notre parser sont obtenues à partir de la grammaire. Dans cet exemple, on commence la construction de l'arbre d’analyse avec la production qui a comme tête la variable $p$. D’habitude
```suggestion
Les méthodes du notre parser sont obtenues à partir de la grammaire. Dans cet exemple, on commence la construction de l'arbre d’analyse avec la production qui a comme tête la variable $p$. D’habitude, on commence l’analyse avec la régle de début de notre grammaire.
```

2024-03-25 13:32 UTC, Ioan-Cristian commented on docs/tp/05/index.md
> +1. Ouvrez le dossier `TP5/Ex1`. Suivez les `TODO` de la grammaire dans le fichier `app/src/main/antlr/ex1.g4` pour accepter des déclarations des variable ayant la syntaxe suivante:
```suggestion
1. Ouvrez le dossier `TP5/Ex1`. Suivez les `TODO` de la grammaire dans le fichier `app/src/main/antlr/ex1.g4` pour accepter des déclarations de variables ayant la syntaxe suivante:
```

2024-03-26 21:39 UTC, alexandruradovici requested changes

2024-03-26 21:39 UTC, alexandruradovici commented on docs/tp/05/index.md
> +slug: tp/05
```suggestion
slug: /tp/05
```

2024-03-31 07:05 UTC, alexandruradovici requested changes
Looks good, use *analyseur* instead of parser, I modified some.

2024-03-31 07:05 UTC, alexandruradovici commented on docs/tp/05/index.md
> +# 05 - ANTLR Lexer et Parser
```suggestion
# 05 - ANTLR Lexer et Analyseur
```

2024-03-31 07:05 UTC, alexandruradovici commented on docs/tp/05/index.md
> +## Parser
```suggestion
## Analyseur
```

2024-03-31 07:05 UTC, alexandruradovici commented on docs/tp/05/index.md
> +Le Parser obtient la séquence de jétons produite par le Lexer et vérifie si elle peut être générée par la grammaire du langage source. La sortie du Parser est l’arbre d’analyze (Parse Tree). Les erre
```suggestion
L'analyseur obtient la séquence de jétons produite par le Lexer et vérifie si elle peut être générée par la grammaire du langage source. La sortie d'analyseur est l’arbre d’analyze (Parse Tree). Les erreurs qui apparaissent au niveau d'Analyseur sont des **erreurs d’analyse syntaxique**.
```

2024-03-31 07:05 UTC, alexandruradovici commented on docs/tp/05/index.md
> +## Parser et Lexer avec ANTLR
```suggestion
## Analyseur et Lexer avec ANTLR
```

2024-03-31 07:05 UTC, alexandruradovici commented on docs/tp/05/index.md
> +  Les noms du lexer et parser auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusieur
```suggestion
  Les noms du lexer et d'analyseur auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusieurs détails sur ces classes et les méthodes qu’elles exposent, on vous conseille d’ouvrir la documentation: [lexer](https://www.antlr.org/api/Java/org/antlr/v4/runtime/Lexer.html) et [parser](https://www.antlr.org/api/Java/org/antlr/v4/runtime/Parser.html).
```

2024-04-01 15:55 UTC, CAmi307 commented on docs/tp/05/index.md
> +**L'Analyseur** obtient la séquence de jétons produite par le Lexer et vérifie si elle peut être générée par la grammaire du langage source. La sortie du Analyseur est l’arbre d’analyze (Parse Tree).
Could we also add Parser in parantheses? This way it would match with the schema provided downbelow. Otherwise, it might be confusing to identify the described components in the schema.

2024-04-01 15:59 UTC, CAmi307 commented on docs/tp/05/index.md
> +  Les noms du lexer et analyseur auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusi
Extra slash?

```suggestion
  Les noms du lexer et analyseur auront le format suivant: `<nom_de_votre_grammaire>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusieurs détails sur ces classes et les méthodes qu’elles exposent, on vous conseille d’ouvrir la documentation: [lexer](https://www.antlr.org/api/Java/org/antlr/v4/runtime/Lexer.html) et [parser](https://www.antlr.org/api/Java/org/antlr/v4/runtime/Parser.html).
```

2024-04-01 16:02 UTC, CAmi307 commented on docs/tp/05/index.md
> +      viewr.open()
Typo?

```suggestion
      val viewer : TreeViewer = TreeViewer(parser.ruleNames.toMutableList(), tree)
      viewer.open()
```

2024-04-01 16:04 UTC, CAmi307 commented on docs/tp/05/index.md
> +Les types possibles sont `int` et `float`. Les noms des variables sont des chaînes de caractères qui commencent avec un `_` et peuvent contenir des lettres et des chiffres.
That start wih a `_` or that **could** start with a `_`

2024-04-01 16:05 UTC, CAmi307 commented on docs/tp/05/index.md
> +  if(2+3/_variabl){
```suggestion
  if(2+3/_variable){
```

2024-04-01 16:07 UTC, CAmi307 commented on docs/tp/05/index.md
> +    _innvervar = a+b;
```suggestion
    _innervar = a+b;
```

2024-04-01 17:30 UTC, mihaicostin34 commented on docs/tp/05/index.md
> +  Les noms du lexer et analyseur auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusi
It is a needed escape character to mark the < and > (otherwise they are considered html tags and do not show)

2024-04-01 17:34 UTC, mihaicostin34 commented on docs/tp/05/index.md
> +**L'Analyseur** obtient la séquence de jétons produite par le Lexer et vérifie si elle peut être générée par la grammaire du langage source. La sortie du Analyseur est l’arbre d’analyze (Parse Tree).
Done

2024-04-01 17:37 UTC, mihaicostin34 commented on docs/tp/05/index.md
> +  Les noms du lexer et analyseur auront le format suivant: `<nom_de_votre_grammaire\>Lexer` et `<nom_de_votre_grammaire>Parser`. Ils sont des sous-classes des classes Lexer et Parser. Pour voir plusi
Nevermind, it is not

2024-04-01 21:19 UTC, alexandruradovici approved these changes

2024-04-01 21:24 UTC, merged