Add homework placeholder
UPB-FILS-ALF/upb-fils-alf.github.io pull request #7
Opened 2024-02-09 11:36 UTC by alexandruradovici

This pull request adds the homework template.

2024-02-09 14:40 UTC, CAmi307 requested changes

2024-02-09 14:40 UTC, CAmi307 commented on docs/devoir/02.md
> +# Analyse syntaxique
What about "Analyse de la syntaxe"? This option seems to be correct, but i feel that the other option sounds cleaner. What do you think?

2024-02-09 14:57 UTC, mihaicostin34 commented on docs/devoir/02.md
> +# Analyse syntaxique
This also works, but I think that "Analyse syntaxique" matches the next homework's title "Analyse semantique"
Still, both work for me

2024-02-10 10:45 UTC, CAmi307 commented on docs/devoir/02.md
> +# Analyse syntaxique
Ok, fair enough

2024-02-10 10:45 UTC, CAmi307 approved these changes

2024-02-10 10:46 UTC, merged