Tp1
UPB-FILS-ALF/upb-fils-alf.github.io pull request #8
Opened 2024-02-09 15:50 UTC by mihaicostin34

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Mihai Costin <mihaicostin342@gmail.com>

2024-02-10 10:47 UTC, CAmi307 commented on docs/tp/01.md
> +Pendant ce semestre, on va utiliser l’IDE Intellij. Pour installer Kotlin, vérifiez le lien dans la séction “Sources”.
```suggestion
Pendant ce semestre, on va utiliser l’IDE IntelliJ. Pour installer Kotlin, vérifiez le lien dans la séction “Sources”.
```

2024-02-10 14:38 UTC, alexandruradovici requested changes

2024-02-10 14:38 UTC, alexandruradovici commented on docs/tp/Images/01.1.png
I suggest using small letters for folder name, like `images`.

2024-02-10 14:38 UTC, alexandruradovici commented on docs/tp/01.md
> +* [Installation d'Intellij](https://www.jetbrains.com/help/idea/installation-guide.html)
```suggestion
* [Installation d'IntelliJ](https://www.jetbrains.com/help/idea/installation-guide.html)
```

2024-02-10 14:45 UTC, alexandruradovici commented
Blocked until #9 is merged.

2024-02-11 11:20 UTC, mihaicostin34 commented on docs/tp/Images/01.1.png
Solved
Image name has the format <tp_number>_<relevant_name>.png

2024-02-11 11:20 UTC, mihaicostin34 commented on docs/tp/01.md
> +* [Installation d'Intellij](https://www.jetbrains.com/help/idea/installation-guide.html)
Solved

2024-02-11 11:20 UTC, mihaicostin34 commented on docs/tp/01.md
> +Pendant ce semestre, on va utiliser l’IDE Intellij. Pour installer Kotlin, vérifiez le lien dans la séction “Sources”.
Solved

2024-02-12 10:11 UTC, alexandruradovici commented on docs/tp/01.md
> +## Développement
I would place this above the exercises.

2024-02-12 10:11 UTC, alexandruradovici commented
Please fill out the pull request message.

2024-02-12 15:35 UTC, mihaicostin34 commented on docs/tp/01.md
> +## Développement
Solved

2024-02-12 15:37 UTC, alexandruradovici requested changes

2024-02-12 15:37 UTC, alexandruradovici commented on docs/tp/01.md
> +* [Kotlin pour Android](https://kotlinlang.org/docs/android-overview.html)
I would put these two as extra documentation, after the links that are required.

2024-02-12 15:44 UTC, mihaicostin34 commented on docs/tp/01.md
> +* [Kotlin pour Android](https://kotlinlang.org/docs/android-overview.html)
Modified, added necessary links and optional links

2024-02-12 15:44 UTC, alexandruradovici approved these changes

2024-02-12 15:44 UTC, alexandruradovici commented
Looks good, @mihaicostin34 please add it to the merge queue if you think it is good to go.

2024-02-12 15:47 UTC, merged